//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stivious {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScrollBarOriginal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScrollBarOriginal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stivious.ScrollBarOriginal", typeof(ScrollBarOriginal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Fill Brushes --&gt;
        ///
        ///&lt;LinearGradientBrush x:Key=&quot;NormalBrush&quot; StartPoint=&quot;0,0&quot; EndPoint=&quot;0,1&quot;&gt;
        ///  &lt;GradientBrush.GradientStops&gt;
        ///    &lt;GradientStopCollection&gt;
        ///      &lt;GradientStop Color=&quot;#FFF&quot; Offset=&quot;0.0&quot;/&gt;
        ///      &lt;GradientStop Color=&quot;#CCC&quot; Offset=&quot;1.0&quot;/&gt;
        ///    &lt;/GradientStopCollection&gt;
        ///  &lt;/GradientBrush.GradientStops&gt;
        ///&lt;/LinearGradientBrush&gt;
        ///
        ///&lt;LinearGradientBrush x:Key=&quot;HorizontalNormalBrush&quot; StartPoint=&quot;0,0&quot; EndPoint=&quot;1,0&quot;&gt;
        ///  &lt;GradientBrush.GradientStops&gt;
        ///    &lt;GradientStopCollection&gt;
        ///      &lt;Gradi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Brushes {
            get {
                return ResourceManager.GetString("Brushes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Style x:Key=&quot;ScrollBarLineButton&quot; TargetType=&quot;{x:Type RepeatButton}&quot;&gt;
        ///  &lt;Setter Property=&quot;SnapsToDevicePixels&quot; Value=&quot;True&quot;/&gt;
        ///  &lt;Setter Property=&quot;OverridesDefaultStyle&quot; Value=&quot;true&quot;/&gt;
        ///  &lt;Setter Property=&quot;Focusable&quot; Value=&quot;false&quot;/&gt;
        ///  &lt;Setter Property=&quot;Template&quot;&gt;
        ///    &lt;Setter.Value&gt;
        ///      &lt;ControlTemplate TargetType=&quot;{x:Type RepeatButton}&quot;&gt;
        ///        &lt;Border 
        ///          Name=&quot;Border&quot;
        ///          Margin=&quot;1&quot; 
        ///          CornerRadius=&quot;2&quot; 
        ///          Background=&quot;{StaticResource NormalBrush}&quot;
        ///          Border [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScrollBarControlTemplate {
            get {
                return ResourceManager.GetString("ScrollBarControlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Style x:Key=&quot;LeftScrollViewer&quot; TargetType=&quot;{x:Type ScrollViewer}&quot;&gt;
        ///  &lt;Setter Property=&quot;OverridesDefaultStyle&quot; Value=&quot;True&quot;/&gt;
        ///  &lt;Setter Property=&quot;Template&quot;&gt;
        ///    &lt;Setter.Value&gt;
        ///      &lt;ControlTemplate TargetType=&quot;{x:Type ScrollViewer}&quot;&gt;
        ///        &lt;Grid&gt;
        ///          &lt;Grid.ColumnDefinitions&gt;
        ///            &lt;ColumnDefinition Width=&quot;Auto&quot;/&gt;
        ///            &lt;ColumnDefinition/&gt;
        ///          &lt;/Grid.ColumnDefinitions&gt;
        ///          &lt;Grid.RowDefinitions&gt;
        ///            &lt;RowDefinition/&gt;
        ///            &lt;RowDefinition Height=&quot;Auto&quot;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScrollBarViewer {
            get {
                return ResourceManager.GetString("ScrollBarViewer", resourceCulture);
            }
        }
    }
}
